const fs = require('fs');

const rawData = `PENDIDIKAN FISIKA:
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	KU100	PENDIDIKAN AGAMA ISLAM	ISLAMIC EDUCATION	2	1
2	KU101	PENDIDIKAN AGAMA KRISTEN	CHRISTIAN EDUCATION	2	1
3	KU102	PENDIDIKAN AGAMA KATOLIK	CATHOLIC RELIGIOUS EDUCATION	2	1
4	KU103	PENDIDIKAN AGAMA HINDU	HINDU RELIGIOUS EDUCATION	2	1
5	KU104	PENDIDIKAN AGAMA BUDDHA	BUDDHIST EDUCATION	2	1
6	KU105	PENDIDIKAN KEWARGANEGARAAN	CIVIC EDUCATION	2	1
7	KU108	OLAHRAGA DAN KEBUGARAN	SPORT AND FITNESS	2	1
8	KU110	PENDIDIKAN PANCASILA	PANCASILA EDUCATION	2	1
9	KU119	APRESIASI SENI	ART APPRECIATION	2	1
10	KU106	PENDIDIKAN BAHASA INDONESIA	INDONESIAN LANGUAGE EDUCATION	2	1
11	KU109	PENDIDIKAN AGAMA KHONGHUCU	CONFUCIAN RELIGIOUS EDUCATION	2	1
12	KU107	PENDIDIKAN KEPERCAYAAN TERHADAP TUHAN YME	RELIGIOUS BELIEF EDUCATION	2	1
13	KU111	STUDI AGAMA	RELIGIOUS STUDIES	2	1
14	DK300	LANDASAN PENDIDIKAN	FOUNDATIONS OF EDUCATION	2	2
15	KU114	PENDIDIKAN PENGAHAYATAN KEPERCAYAAN	BELIEF APPRECIATION EDUCATION	2	2
16	KU315	SEMINAR PENDIDIKAN PENGHAYATAN KEPERCAYAAN	SEMINAR OF BELIEF APPRECIATION EDUCATION	2	2
17	KU300	SEMINAR PENDIDIKAN AGAMA ISLAM	ISLAMIC RELIGIOUS EDUCATION SEMINAR	2	3
18	KU302	SEMINAR PENDIDIKAN AGAMA KRISTEN KATOLIK	CATHOLIC RELIGIOUS EDUCATION SEMINAR	2	3
19	KU301	SEMINAR PENDIDIKAN AGAMA KRISTEN	CHRISTIAN RELIGIOUS EDUCATION SEMINAR	2	3
20	KU303	SEMINAR PENDIDIKAN AGAMA HINDU	HINDU RELIGIOUS EDUCATION SEMINAR	2	3
21	KU304	SEMINAR PENDIDIKAN AGAMA BUDDHA	BUDDHIST RELIGIOUS EDUCATION SEMINAR	2	3
22	KU309	SEMINAR PENDIDIKAN AGAMA KHONGHUCU	CONFUCIAN RELIGIOUS EDUCATION SEMINAR	2	3
23	MA500	MSTR UNTUK PEMBANGUNAN BERKELANJUTAN	STEM FOR SUSTAINABLE DEVELOPMENT	3	5
Pengembangan Kompetensi Dasar Kependidikan (PKDK)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	DK301	PSIKOLOGI PENDIDIKAN DAN BIMBINGAN	EDUCATIONAL PSYCHOLOGY AND COUNSELLING	2	2
2	DK303	KURIKULUM DAN PEMBELAJARAN	CURRICULUM AND INSTRUCTION	2	2
3	DK302	PENGELOLAAN KELAS	CLASSROOM MANAGEMENT	2	2
4	DK305	PERENCANAAN PEMBELAJARAN	A LEARNING PLAN	3	3
5	DK306	STRATEGI PEMBELAJARAN	LEARNING STRATEGIES	3	3
6	DK310	EVALUASI PEMBELAJARAN	LEARNING EVALUATION	3	3
Pengembangan Keahlian Program Studi (PKPS)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	FI110	FISIKA MATEMATIKA I	MATHEMATICS FOR PHYSICS I	6	1
2	FI115	FISIKA DASAR I	FUNDAMENTALS OF PHYSICS I	4	1
3	FI137	FISIKA BUMI DAN ANTARIKSA	EARTH AND SPACE SCIENCE	3	1
4	FI111	Matematika Dasar untuk Fisika	Mathematical Foundations for Physics	3	1
5	FI231	LITERASI ICT DAN MEDIA PEMBELAJARAN	MEDIA AND ICT LITERACY IN PHYSICS LEARNING	3	2
6	FI312	ELEKTRONIKA	ELECTRONICS	3	2
7	FI310	MEKANIKA	MECHANICS	4	2
8	FI116	FISIKA DASAR II	FUNDAMENTALS OF PHYSICS II	4	2
9	FI114	Fisika Matematika I	Mathematics for Physics I	4	2
10	FI215	EKSPERIMEN FISIKA DASAR	BASIC PHYSICS EXPERIMENTS	4	3
11	FI318	FISIKA MATEMATIKA II	MATHEMATICS FOR PHYSICS II	4	3
12	FI352	TERMODINAMIKA	THERMODYNAMICS	3	3
13	FI351	PEDAGOGI MEKANIKA	PEDAGOGY OF MECHANICS	3	3
14	FI314	GELOMBANG DAN OPTIKA	WAVES AND OPTICS	4	4
15	FI313	LISTRIK MAGNET	ELECTRICITY AND MAGNETISM	4	4
16	FI358	PEDAGOGI LISTRIK, GELOMBANG, DAN FISIKA MODERN	PEDAGOGY OF ELECTRICITY, WAVES, AND MODERN PHYSICS	4	4
17	PT400	KETERAMPILAN BERBAHASA INGGRIS	ENGLISH LANGUAGE SKILLS	3	4
18	FI315	FISIKA MODERN	MODERN PHYSICS	4	5
19	FI411	MANAJEMEN LABORATORIUM PENDIDIKAN FISIKA	PHYSICS EDUCATION LABORATORY MANAGEMENT	3	5
20	FI512	FISIKA INTI	NUCLEAR PHYSICS	4	5
21	FI510	FISIKA KUANTUM	QUANTUM PHYSICS	3	6
22	FI511	FISIKA ZAT PADAT	SOLID STATE PHYSICS	3	6
23	FI410	METODOLOGI PENELITIAN DAN PENULISAN ILMIAH PENDIDIKAN FISIKA	RESEARCH METHODOLOGY AND SCIENTIFIC WRITING IN PHYSICS EDUCATION	4	6
24	FI412	EKSPERIMEN FISIKA	PHYSICS EXPERIMENTS	3	6
25	FI374	WIRAUSAHA MUDA BERBASIS INTELEGENSI	INTELLIGENCE-BASED YOUNG ENTREPRENEURS	4	6
26	FI532	KREASI KONTEN DIGITAL PEMBELAJARAN FISIKA	PHYSICS LEARNING DIGITAL CONTENT CREATION	4	6
27	FI558	METROLOGI DAN KALIBRASI	METROLOGY AND CALLIBRATION	4	6
28	FI437	FISIKA KOMPUTASI	COMPUTATIONAL PHYSICS	4	6
29	FI438	EKSPERIMEN FISIKA BERBASIS LINGKUNGAN DAN KOMPUTER	COMPUTER ASSISTED AND ENVIRONMENTAL BASED PHYSICS EXPERIMENTS	4	6
30	FI531	TEORI RESPON BUTIR	ITEM RESPONSE THEORY	4	7
31	FI372	FISIKA MEDIS	MEDICAL PHYSICS	4	7
32	FI151	FISIKA UNTUK PENDIDIKAN DASAR	PHYSICS FOR ELEMENTARY SCHOOL	4	7
33	FI413	E-LEARNING FISIKA	E-LEARNING IN PHYSICS EDUCATION	4	7
34	FI373	TAKSONOMI PENDIDIKAN FISIKA	TAXONOMY IN PHYSICS EDUCATION	4	7
35	FI533	PENGEMBANGAN BAHAN AJAR FISIKA	PHYSICS TEACHING LEARNING MATERIAL DEVELOPMENT	4	7
36	FI534	PENGEMBANGAN PRAKTIKUM FISIKA SEKOLAH	DEVELOPMENT OF SCHOOL PHYSICS PRACTICUM	4	7
37	FI535	PSIKOLOGI KOGNITIF DALAM PEMBELAJARAN FISIKA	COGNITIVE PSYCHOLOGY IN PHYSICS LEARNING	4	7
38	FI537	TPACK FISIKA	TPACK IN PHYSICS EDUCATION	4	7
39	FI538	PENDIDIKAN FISIKA INKLUSIF	INCLUSIVE PHYSICS EDUCATION	4	7
40	FI557	FILSAFAT PENDIDIKAN FISIKA	PHILOSOPHY OF PHYSICS EDUCATION	4	7
41	FI556	PENDIDIKAN FISIKA UNTUK LINGKUNGAN DAN PEMBANGUNAN BERKELANJUTAN	PHYSICS EDUCATION FOR ENVIRONMENT AND SUSTAINABLE DEVELOPMENT	4	7
42	FI439	TEKNOLOGI DAN REKAYASA DALAM PENDIDIKAN FISIKA	TECHNOLOGY AND ENGINEERING IN PHYSICS EDUCATION	4	7
43	FI515	FISIKA STATISTIK *)	STATISTICAL PHYSICS *)	3	7
44	FI514	PENDAHULUAN FISIKA INTI	INTRODUCTION TO NUCLEAR PHYSICS	3	7
45	KA591	SKRIPSI	UNDERGRADUATE THESIS	6	7
46	KA592	ARTIKEL ILMIAH	SCIENTIFIC ARTICLES	6	7
Pengembangan Keterampilan Bidang Keahlian (PKBK)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	PT501	PEMBELAJARAN MICRO	MICROTEACHING	4	5
Pengembangan Jiwa Kewirausahaan (PJK)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	PT503	KEWIRAUSAHAAN	ENTREPRENEURSHIP	3	4
2	PT504	KREDENSIAL MIKRO KEWIRAUSAHAAN	MICRO-CREDENTIALS IN ENTREPRENEURSHIP	3	4
Penguatan Kompetensi Lanjutan (PKL)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	LN806	LITERASI ARTIFICIAL INTELLIGENCE	ARTIFICIAL INTELLIGENCE LITERACY	3	3
2	KM459	PENDIDIKAN ANTI KORUPSI	ANTI-CORRUPTION EDUCATION	4	3
3	KM417	PRAKTIK MENGAJAR	TEACHING PRACTICE	8	6
4	KM418	PENGEMBANGAN BAHAN AJAR DAN MEDIA PENDIDIKAN	DEVELOPMENT OF TEACHING MATERIALS AND EDUCATIONAL MEDIA	4	6
5	KM419	PRAKTIK PENILAIAN HASIL BELAJAR	LEARNING OUTCOME ASSESMENT PRACTICES	4	6
6	KM420	PRAKTIK MANAJEMEN SEKOLAH	SCHOOL MANAGEMENT PRACTICES	4	6
7	KM421	PENGEMBANGAN EKSTRAKURIKULER	EXTRACURRICULAR DEVELOPMENT	4	6
8	KM422	BERFIKIR KRITIS DAN KREATIF	CREATIVE AND CRITICAL THINKING	4	6
9	KM423	KEPEMIMPINAN BERWAWASAN BELA NEGARA	LEADERSHIP WITH NATIONAL DEFENSE	4	6
10	KM424	KEPEMIMPINAN INKLUSIF & INOVATIF	INCLUSIVE & INNOVATIVE LEADERSHIP	4	6
11	KM425	KETERAMPILAN DASAR BELA NEGARA	BASIC NATIONAL DEFENSE SKILLS	4	6
12	KM426	KOMUNIKASI DAN KERJASAMA TIM	COMMUNICATION AND TEAMWORK	4	6
13	KM427	NILAI-NILAI DASAR BELA NEGARA	BASIC VALUES OF NATIONAL DEFENSE	4	6
14	KM428	PEMBANGUNAN KARAKTER BANGSA	NATIONAL CHARACTER DEVELOPMENT	4	6
15	KM429	PEMECAHAN MASALAH KOMPLEKS	COMPLEX PROBLEM SOLVING	4	6
16	KM430	REKONSILIASI DAN RESOLUSI KONFLIK	RECONCILIATION AND CONFLICT RESOLUTION	4	6
17	KM431	PATRIOTISME BELA NEGARA	NATIONAL PATRIOTISM	4	6
18	KM432	NEGOSIASI ORGANISASI	ORGANIZATIONAL NEGOTIATIONS	4	6
19	KM433	STUDI MITIGASI BENCANA	DISASTER MITIGATION STUDY	4	6
20	KM434	STUDI SDG'S	STUDY SUSTAINABLE DEVELOPMENT GOALS (SDG's)	4	6
21	KM435	KETERAMPILAN MENULIS AKADEMIK	ACADEMIC WRITING SKILLS	4	6
22	KM436	KEPEMIMPINAN BERBASIS KOMUNITAS	COMMUNITY-BASED LEADERSHIP	4	6
23	KM437	EKONOMI KREATIF	CREATIVE ECONOMY	4	6
24	KM438	DESAIN PENELITIAN	RESEARCH DESIGN	4	6
25	KM439	KEWIRAUSAHAAN PENDIDIKAN	EDU-ENTREPRENEURSHIP	4	6
26	KM440	ETIKA PROFESI	PROFESSIONAL ETHICS	4	6
27	KM442	EEKONOMI BERBASIS PENGETAHUAN	KNOWLEDGE-BASED ECONOMY	4	6
28	KM443	LITERASI EKONOMI DIGITAL	DIGITAL ECONOMY LITERACY	4	6
29	KM446	PENGEMBANGAN PRODUK STARTUP	START-UP PRODUCT DEVELOPMENT	4	6
30	KM447	DISEMINASI HASIL PENELITIAN	DISSEMINATION OF RESEARCH RESULTS	4	6
31	KM448	STRATEGI PENGEMBANGAN DIRI	SELF- DEVELOPMENT STRATEGY	4	6
32	KM449	STUDI INDEPENDEN TEMATIK	THEMATIC INDEPENDENT STUDY	4	6
33	KM451	MANAJEMEN MUTU TOTAL	TOTAL QUALITY MANAGEMENT (TQM)	4	6
34	KM452	MANAJEMEN RISIKO	RISK MANAGEMENT	4	6
35	KM453	PENGEMBANGAN KOMPETENSI DAN PROFESI	COMPETENCY AND PROFESSIONAL DEVELOPMENT	4	6
36	KM455	TEKNOLOGI INDUSTRI 4.0	INDUSTRY 4.0 TECHNOLOGY	4	6
37	KM456	PENGUATAN INOVASI INDUSTRI	STRENGTHENING INDUSTRIAL INNOVATION	4	6
38	KM457	TINJAUAN PUSTAKA	LITERATURE REVIEW	4	6
39	KM415	DESAIN PEMBELAJARAN	LEARNING DESIGN	4	6
40	KM416	PENERAPAN STRATEGI PEMBELAJARAN	IMPLEMENTATION OF LEARNING STRATEGIES	4	6
41	KM441	MANAJEMEN WIRAUSAHA	ENTREUPRENEURIAL MANAGEMENT	4	6
42	KM445	PENELITIAN BERBANTUAN TEKNOLOGI	TECHNOLOGY ASSISTED RESEARCH	4	6
43	KM450	TEKNIK ANALISIS DATA	DATA ANALYSIS TECHNIQUE	4	6
44	KM444	MANAJEMEN PROJEK DAN JARINGAN	PROJECT AND NETWORK MANAGEMENT	4	6
45	KM454	DISRUPSI: MASALAH DAN PELUANGNYA	DISRUPTION: PROBLEMS AND OPPORTUNITIES	4	6
46	KM412	MODUL NUSANTARA	ARCHIPELAGO MODULE	4	6


FISIKA:
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	KU100	PENDIDIKAN AGAMA ISLAM	ISLAMIC EDUCATION	2	1
2	KU101	PENDIDIKAN AGAMA KRISTEN	CHRISTIAN EDUCATION	2	1
3	KU102	PENDIDIKAN AGAMA KATOLIK	CATHOLIC RELIGIOUS EDUCATION	2	1
4	KU103	PENDIDIKAN AGAMA HINDU	HINDU RELIGIOUS EDUCATION	2	1
5	KU104	PENDIDIKAN AGAMA BUDDHA	BUDDHIST EDUCATION	2	1
6	KU105	PENDIDIKAN KEWARGANEGARAAN	CIVIC EDUCATION	2	1
7	KU108	OLAHRAGA DAN KEBUGARAN	SPORT AND FITNESS	2	1
8	KU110	PENDIDIKAN PANCASILA	PANCASILA EDUCATION	2	1
9	KU119	APRESIASI SENI	ART APPRECIATION	2	1
10	KU106	PENDIDIKAN BAHASA INDONESIA	INDONESIAN LANGUAGE EDUCATION	2	1
11	KU109	PENDIDIKAN AGAMA KHONGHUCU	CONFUCIAN RELIGIOUS EDUCATION	2	1
12	KU107	PENDIDIKAN KEPERCAYAAN TERHADAP TUHAN YME	RELIGIOUS BELIEF EDUCATION	2	1
13	KU111	STUDI AGAMA	RELIGIOUS STUDIES	2	1
14	DK300	LANDASAN PENDIDIKAN	FOUNDATIONS OF EDUCATION	2	2
15	KU114	PENDIDIKAN PENGAHAYATAN KEPERCAYAAN	BELIEF APPRECIATION EDUCATION	2	2
16	KU315	SEMINAR PENDIDIKAN PENGHAYATAN KEPERCAYAAN	SEMINAR OF BELIEF APPRECIATION EDUCATION	2	2
17	KU300	SEMINAR PENDIDIKAN AGAMA ISLAM	ISLAMIC RELIGIOUS EDUCATION SEMINAR	2	3
18	KU302	SEMINAR PENDIDIKAN AGAMA KRISTEN KATOLIK	CATHOLIC RELIGIOUS EDUCATION SEMINAR	2	3
19	KU301	SEMINAR PENDIDIKAN AGAMA KRISTEN	CHRISTIAN RELIGIOUS EDUCATION SEMINAR	2	3
20	KU303	SEMINAR PENDIDIKAN AGAMA HINDU	HINDU RELIGIOUS EDUCATION SEMINAR	2	3
21	KU304	SEMINAR PENDIDIKAN AGAMA BUDDHA	BUDDHIST RELIGIOUS EDUCATION SEMINAR	2	3
22	KU309	SEMINAR PENDIDIKAN AGAMA KHONGHUCU	CONFUCIAN RELIGIOUS EDUCATION SEMINAR	2	3
23	MA500	MSTR UNTUK PEMBANGUNAN BERKELANJUTAN	STEM FOR SUSTAINABLE DEVELOPMENT	3	5
Pengembangan Keahlian Program Studi (PKPS)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	FI201	MATEMATIKA UNTUK FISIKA DASAR	BASIC PHYSICS MATHEMATICS	4	1
2	FI100	FISIKA DASAR I	BASIC PHYSICS I	4	1
3	FI202	ALGORITMA DAN PEMROGRAMAN	ALGHORITM AND PROGRAMMING	3	1
4	FI101	FISIKA DASAR II	BASIC PHYSICS II	4	2
5	FI102	FISIKA BUMI DAN ANTARIKSA	EARTH AND SPACE PHYSICS	4	2
6	FI204	MATEMATIKA FISIKA I	MATHEMATICAL PHYSICS 1	4	2
7	FI203	EKSPERIMEN FISIKA DASAR	BASIC PHYSICS EXPERIMENT	4	2
8	FI302	TERMODINAMIKA	THERMODYNAMICS	3	2
9	FI103	KONSEP DASAR BUMI DAN ANTARIKSA	BASIC CONCEPTS OF EARTH AND SPACE	3	2
10	FI205	MATEMATIKA FISIKA II	MATHEMATICAL PHYSICS II	4	3
11	FI206	ELEKTRONIKA ANALOG	ANALOG ELECTRONICS	4	3
12	FI300	MEKANIKA	MECHANICS	4	3
13	FI301	FISIKA MODERN	MODERN PHYSICS	4	3
14	FI207	MATEMATIKA FISIKA II	MATHEMATICAL PHYSICS II	3	3
15	FI208	ELEKTRONIKA ANALOG	ANALOG ELECTRONICS	3	3
16	FI209	TEKNOLOGI INFORMASI DAN KOMUNIKASI	INFORMATION AND COMMUNICATION TECHNOLOGY	2	3
17	FI540	TEORI RELATIVITAS	THEORY OF RELATIVITY	4	4
18	FI400	EKSPERIMEN FISIKA LANJUT	ADVANCED PHYSICS EXPERIMENTS	4	4
19	FI303	LISTRIK MAGNET	ELECTRICITY AND MAGNETISME	4	4
20	FI304	GELOMBANG	WAVE	4	4
21	FI401	ELEKTRONIKA DIGITAL	DIGITAL ELECTRONICS	4	4
22	FI320	GEOLOGI GEOFISIKA	GEOLOGY GEOPHYSICS	4	4
23	FI322	FISIKA MATERIAL	MATERIAL PHYSICS	4	4
24	FI323	METROLOGI DAN KALIBRASI	METROLOGY AND CALIBRATION	4	4
25	FI321	TATA SURYA	SOLAR SYSTEM	4	4
26	FI403	EKSPERIMEN FISIKA MODERN	MODERN PHYSICS EXPERIMENT	3	4
27	FI404	ELEKTRONIKA DIGITAL	DIGITAL ELECTRONICS	3	4
28	FI305	GEOLOGI GEOFISIKA	GEOLOGY GEOPHYSICS	3	4
29	FI307	FISIKA MATERIAL	MATERIAL PHYSICS	3	4
30	FI308	METROLOGI DAN KALIBRASI	METROLOGY AND CALIBRATION	3	4
31	FI306	FISIKA ANTARIKSA	SPACE PHYSICS	3	4
32	FI326	SEJARAH FISIKA	HISTORY OF PHYSICS	2	4
33	FI325	OPTIKA	OPTICS	2	4
34	PT400	KETERAMPILAN BERBAHASA INGGRIS	ENGLISH LANGUAGE SKILLS	3	4
35	FI541	TEORI GRUP DAN SIMETRI	GROUP THEORY AND SYMMETRY	4	5
36	FI402	FISIKA KOMPUTASI	COMPUTATIONAL PHYSICS	4	5
37	FI500	FISIKA KUANTUM	QUANTUM PHYSICS	4	5
38	FI520	EKSPLORASI GEOFISIKA	GEOPHYSICS EXPLORATION	4	5
39	FI524	FISIKA PIRANTI SEMIKONDUKTOR	PHYSICS OF SEMICONDUCTOR DEVICE	4	5
40	FI526	SISTEM INSTRUMENTASI	INSTRUMENTATION SYSTEM	4	5
41	FI522	FISIKA BINTANG	STELLAR PHYSICS	4	5
42	FI528	FISIKA PANAS BUMI	GEOTHERMAL PHYSICS	2	5
43	FI507	GALAKSI DAN KOSMOLOGI	GALAXIES AND COSMOLOGY	3	5
44	FI529	ASTRONOMI POSISI	POSITIONAL ASTRONOMY	2	5
45	FI508	FISIKA PIRANTI SEMIKONDUKTOR	PHYSICS OF SEMICONDUCTOR DEVICE	3	5
46	FI547	NANOMATERIAL	NANOMATERIAL	2	5
47	FI509	SISTEM INSTRUMENTASI	INSTRUMENTATION SYSTEM	3	5
48	FI548	INSTRUMENTASI CERDAS	INTELLIGENT INSTRUMENTATION	2	5
49	FI407	EKSPLORASI GEOFISIKA	GEOPHYSICS EXPLORATION	3	5
50	FI340	FISIKA GUNUNG API	VOLCANO PHYSICS	2	5
51	FI341	FISIKA BENCANA ALAM	PHYSICS OF NATURAL DISASTERS	2	5
52	FI344	ASTRONOMI DAN LINGKUNGAN	ASTRONOMY AND THE ENVIRONMENT	2	5
53	FI345	SISTEM KALENDER	CALENDAR SYSTEM	2	5
54	FI381	FISIKA MEDIS	MEDICAL PHYSICS	2	5
55	FI384	KOMPUTASI MATERIAL	MATERIAL COMPUTATION	2	5
56	FI380	OTOMASI DAN KENDALI	AUTOMATION AND CONTROL	2	5
57	FI385	SAINS DAN TEKNOLOGI SEL SURYA	SOLAR CELL SCIENCE AND TECHNOLOGY	2	5
58	FI309	TEORI RELATIVITAS	THEORY OF RELATIVITY	2	5
59	FI587	TEORI GRUP DAN SIMETRI	GROUP THEORY AND SYMMETRY	2	5
60	FI405	EKSPERIMEN LISTRIK MAGNET DAN GELOMBANG	WAVE AND ELECTROMAGNETIC EXPERIMENT	2	5
61	FI560	GEOMEKANIKA TANAH DAN BATUAN	GEOMECHANICS OF SOIL AND ROCK	4	6
62	FI542	FISIKA PARTIKEL	PARTICLE PHYSICS	4	6
63	FI367	SEJARAH FISIKA	HISTORY OF PHYSICS	4	6
64	FI502	FISIKA ZAT PADAT	SOLID-STATE PHYSICS	4	6
65	FI503	FISIKA INTI	NUCLEAR PHYSYCS	4	6
66	FI501	FISIKA STATISTIK	STATISTICAL PHYSICS	4	6
67	FI565	FUNGSIONALISASI MATERIAL	MATERIAL FUNCTIONALIZATION	4	6
68	FI360	FISIKA BENCANA ALAM	PHYSICS OF NATURAL DISASTERS	4	6
69	FI362	SISTEM KALENDER	CALENDAR SYSTEM	4	6
70	FI364	OTOMASI DAN KENDALI	AUTOMATION AND CONTROL	4	6
71	FI361	ASTRONOMI DAN LINGKUNGAN	ASTRONOMY AND THE ENVIRONMENT	4	6
72	FI561	METEOROLOGI DAN CUACA ANTARIKSA	METEOROLOGY AND SPACE WEATHER	4	6
73	FI545	KOMPUTASI MATERIAL	MATERIAL COMPUTATION	4	6
74	FI564	SAINS DAN TEKNOLOGI SEL SURYA	SOLAR CELL SCIENCE AND TECHNOLOGY	4	6
75	FI523	GALAKSI DAN KOSMOLOGI	GALAXIES AND COSMOLOGY	4	6
76	FI543	ANALISIS DATA GEOFISIKA	DATA ANALYSIS ON GEOPHYSICS	4	6
77	FI521	FISIKA PANAS BUMI	GEOTHERMAL PHYSICS	4	6
78	FI363	ASTRONOMI POSISI	POSITIONAL ASTRONOMY	4	6
79	FI544	NANOMATERIAL	NANOMATERIAL	4	6
80	FI525	PEMROSESAN DAN KARAKTERISASI BAHAN SEMIKONDUKTOR	PROCESSING AND CHARACTERIZATION OF SEMICONDUCTOR MATERIAL	4	6
81	FI527	INSTRUMENTASI CERDAS	INTELLIGENT INSTRUMENTATION	4	6
82	FI365	FISIKA MEDIS	MEDICAL PHYSICS	4	6
83	FI562	MEKANIKA BENDA LANGIT	MECHANICS OF CELESTIAL BODIES	4	6
84	FI566	SUPERKONDUKTOR	SUPERCONDUCTOR	4	6
85	FI366	INSTRUMENTASI OPTIK	OPTICAL INSTRUMENTATION	4	6
86	FI546	APLIKASI MIKROPROSESOR	MICROPROCESSOR APPLICATIONS	4	6
87	FI563	INSTRUMENTASI INDUSTRI	INDUSTRIAL INSTRUMENTATION	4	6
88	FI549	ANALISIS DATA GEOFISIKA	DATA ANALYSIS ON GEOPHYSICS	3	6
89	FI567	FISIKA BINTANG	STELLAR PHYSICS	3	6
90	FI568	PEMROSESAN DAN KARAKTERISASI BAHAN SEMIKONDUKTOR	PROCESSING AND CHARACTERIZATION OF SEMICONDUCTOR MATERIAL	3	6
91	FI569	APLIKASI MIKROPROSESOR	MICROPROCESSOR APPLICATIONS	3	6
92	FI406	FISIKA STATISTIK	STATISTICAL PHYSICS	3	6
93	FI342	GEOMEKANIKA TANAH DAN BATUAN	GEOMECHANICS OF SOIL AND ROCK	2	6
94	FI343	METEOROLOGI DAN CUACA ANTARIKSA	METEOROLOGY AND SPACE WEATHER	2	6
95	FI346	TATA SURYA	SOLAR SYSTEM	2	6
96	FI347	MEKANIKA BENDA LANGIT	MECHANICS OF CELESTIAL BODIES	2	6
97	FI382	INSTRUMENTASI OPTIK	OPTICAL INSTRUMENTATION	2	6
98	FI383	INSTRUMENTASI INDUSTRI	INDUSTRIAL INSTRUMENTATION	2	6
99	FI386	FUNGSIONALISASI MATERIAL	MATERIAL FUNCTIONALIZATION	2	6
100	FI387	SUPERKONDUKTOR	SUPERCONDUCTOR	2	6
101	FI588	FISIKA PARTIKEL	PARTICLE PHYSICS	2	6
102	KA591	SKRIPSI	UNDERGRADUATE THESIS	6	7
103	KA592	ARTIKEL ILMIAH	SCIENTIFIC ARTICLES	6	7
104	KA593	PROTOTYPE MENENGAH PRODUK INDUSTRI	INDUSTRIAL PRODUCT INTERMEDIATE PROTOTYPE	6	7
105	KA594	PROYEK SENI MONUMENTAL TINGKAT DASAR	ELEMENTARY LEVEL MONUMENTAL ART PROJECT	6	7
106	KA595	PROYEK SENI DESAIN	ART DESIGN PROJECT	6	7
107	KA596	PROYEK TEKNOLOGI TEPAT GUNA	APPROPRIATE TECHNOLOGY PROJECT	6	7
108	KA597	PROYEK TEKNOLOGI KEPENDIDIKAN	EDUCATIONAL TECHNOLOGY PROJECT	6	7
109	KA598	PROYEK PRODUK BISNIS	BUSINESS PRODUCT PROJECT	6	7
110	KA599	PROYEK PRODUK KREATIF SARJANA	UNDERGRADUATE CREATIVE PRODUCT PROJECT	6	7
111	KA600	PORTOFOLIO PENCAPAIAN PRESTASI	ACHIEVEMENT PORTPORTFOLIO	6	7
112	FI504	METODE RISET DAN PUBLIKASI ILMIAH	RESEARCH METHODOLOGY AND SCIENTIFIC PUBLICATION	4	8
Pengembangan Keterampilan Bidang Keahlian (PKBK)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	PT502	PROYEK KONSULTANSI	CONSULTANCY PROJECT	4	5
Pengembangan Jiwa Kewirausahaan (PJK)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	PT503	KEWIRAUSAHAAN	ENTREPRENEURSHIP	3	4
2	PT504	KREDENSIAL MIKRO KEWIRAUSAHAAN	MICRO-CREDENTIALS IN ENTREPRENEURSHIP	3	4
3	PT505	MOJI-GOI	KANJI AND VOCABLURY	3	4
4	PT506	CHOUKAI	LISTENING COMPREHENSION	3	4
5	PT508	DOKKAI	READING COMPREHENSION	3	4
6	PT507	BUNPOU	GRAMMAR	3	4
Penguatan Kompetensi Lanjutan (PKL)
Kode MK	Kode MK	Nama MK	Nama MK Inggris	SKS	Semester
1	LN806	LITERASI ARTIFICIAL INTELLIGENCE	ARTIFICIAL INTELLIGENCE LITERACY	3	3
2	KM459	PENDIDIKAN ANTI KORUPSI	ANTI-CORRUPTION EDUCATION	4	3
3	KM417	PRAKTIK MENGAJAR	TEACHING PRACTICE	8	6
4	KM418	PENGEMBANGAN BAHAN AJAR DAN MEDIA PENDIDIKAN	DEVELOPMENT OF TEACHING MATERIALS AND EDUCATIONAL MEDIA	4	6
5	KM419	PRAKTIK PENILAIAN HASIL BELAJAR	LEARNING OUTCOME ASSESMENT PRACTICES	4	6
6	KM420	PRAKTIK MANAJEMEN SEKOLAH	SCHOOL MANAGEMENT PRACTICES	4	6
7	KM421	PENGEMBANGAN EKSTRAKURIKULER	EXTRACURRICULAR DEVELOPMENT	4	6
8	KM422	BERFIKIR KRITIS DAN KREATIF	CREATIVE AND CRITICAL THINKING	4	6
9	KM423	KEPEMIMPINAN BERWAWASAN BELA NEGARA	LEADERSHIP WITH NATIONAL DEFENSE	4	6
10	KM424	KEPEMIMPINAN INKLUSIF & INOVATIF	INCLUSIVE & INNOVATIVE LEADERSHIP	4	6
11	KM425	KETERAMPILAN DASAR BELA NEGARA	BASIC NATIONAL DEFENSE SKILLS	4	6
12	KM426	KOMUNIKASI DAN KERJASAMA TIM	COMMUNICATION AND TEAMWORK	4	6
13	KM427	NILAI-NILAI DASAR BELA NEGARA	BASIC VALUES OF NATIONAL DEFENSE	4	6
14	KM428	PEMBANGUNAN KARAKTER BANGSA	NATIONAL CHARACTER DEVELOPMENT	4	6
15	KM429	PEMECAHAN MASALAH KOMPLEKS	COMPLEX PROBLEM SOLVING	4	6
16	KM430	REKONSILIASI DAN RESOLUSI KONFLIK	RECONCILIATION AND CONFLICT RESOLUTION	4	6
17	KM431	PATRIOTISME BELA NEGARA	NATIONAL PATRIOTISM	4	6
18	KM432	NEGOSIASI ORGANISASI	ORGANIZATIONAL NEGOTIATIONS	4	6
19	KM433	STUDI MITIGASI BENCANA	DISASTER MITIGATION STUDY	4	6
20	KM434	STUDI SDG'S	STUDY SUSTAINABLE DEVELOPMENT GOALS (SDG's)	4	6
21	KM435	KETERAMPILAN MENULIS AKADEMIK	ACADEMIC WRITING SKILLS	4	6
22	KM436	KEPEMIMPINAN BERBASIS KOMUNITAS	COMMUNITY-BASED LEADERSHIP	4	6
23	KM437	EKONOMI KREATIF	CREATIVE ECONOMY	4	6
24	KM438	DESAIN PENELITIAN	RESEARCH DESIGN	4	6
25	KM439	KEWIRAUSAHAAN PENDIDIKAN	EDU-ENTREPRENEURSHIP	4	6
26	KM440	ETIKA PROFESI	PROFESSIONAL ETHICS	4	6
27	KM442	EEKONOMI BERBASIS PENGETAHUAN	KNOWLEDGE-BASED ECONOMY	4	6
28	KM443	LITERASI EKONOMI DIGITAL	DIGITAL ECONOMY LITERACY	4	6
29	KM446	PENGEMBANGAN PRODUK STARTUP	START-UP PRODUCT DEVELOPMENT	4	6
30	KM447	DISEMINASI HASIL PENELITIAN	DISSEMINATION OF RESEARCH RESULTS	4	6
31	KM448	STRATEGI PENGEMBANGAN DIRI	SELF- DEVELOPMENT STRATEGY	4	6
32	KM449	STUDI INDEPENDEN TEMATIK	THEMATIC INDEPENDENT STUDY	4	6
33	KM451	MANAJEMEN MUTU TOTAL	TOTAL QUALITY MANAGEMENT (TQM)	4	6
34	KM452	MANAJEMEN RISIKO	RISK MANAGEMENT	4	6
35	KM453	PENGEMBANGAN KOMPETENSI DAN PROFESI	COMPETENCY AND PROFESSIONAL DEVELOPMENT	4	6
36	KM455	TEKNOLOGI INDUSTRI 4.0	INDUSTRY 4.0 TECHNOLOGY	4	6
37	KM456	PENGUATAN INOVASI INDUSTRI	STRENGTHENING INDUSTRIAL INNOVATION	4	6
38	KM457	TINJAUAN PUSTAKA	LITERATURE REVIEW	4	6
39	KM415	DESAIN PEMBELAJARAN	LEARNING DESIGN	4	6
40	KM416	PENERAPAN STRATEGI PEMBELAJARAN	IMPLEMENTATION OF LEARNING STRATEGIES	4	6
41	KM441	MANAJEMEN WIRAUSAHA	ENTREUPRENEURIAL MANAGEMENT	4	6
42	KM445	PENELITIAN BERBANTUAN TEKNOLOGI	TECHNOLOGY ASSISTED RESEARCH	4	6
43	KM450	TEKNIK ANALISIS DATA	DATA ANALYSIS TECHNIQUE	4	6
44	KM444	MANAJEMEN PROJEK DAN JARINGAN	PROJECT AND NETWORK MANAGEMENT	4	6
45	KM454	DISRUPSI: MASALAH DAN PELUANGNYA	DISRUPTION: PROBLEMS AND OPPORTUNITIES	4	6
46	KM412	MODUL NUSANTARA	ARCHIPELAGO MODULE	4	6
47	FI581	ASISTENSI LABORATORIUM FISIKA	PHYSICS LABORATORY ASSISTANCE	5	7
48	FI582	VISUALISASI DAN KOMUNIKASI DATA FISIKA	PHYSICS DATA VISUALIZATION AND COMMUNICATION	5	7
49	FI583	KECERDASAN ARTIFISIAL DAN SAINS DATA	ARTIFICIAL INTELLIGENCE AND DATA SCIENCE	5	7
50	FI585	EKONOFISIKA	ECONOPHYSICS	5	7
51	FI584	INOVASI FISIKA	INNOVATION IN PHYSICS	5	7
52	FI586	PRAKTIK PENGALAMAN LAPANGAN	INTERNSHIP	5	7`;

function parseData() {
    const lines = rawData.split('\n');
    let currentProdi = '';
    let currentKategori = 'Wajib';
    const sqlValuesMap = new Map();

    for (const line of lines) {
        let tLine = line.trim();
        if (!tLine) continue;

        if (tLine === 'PENDIDIKAN FISIKA:') {
            currentProdi = 'PendFisika';
            currentKategori = 'Wajib';
            continue;
        } else if (tLine === 'FISIKA:') {
            currentProdi = 'Fisika';
            currentKategori = 'Wajib';
            continue;
        }

        if (!tLine.includes('\t') && tLine.includes('(') && tLine.includes(')')) {
            const match = tLine.match(/\((.*?)\)/);
            if (match) {
                currentKategori = match[1];
            }
            continue;
        }

        if (tLine.startsWith('Kode MK\tKode MK')) {
            continue;
        }

        const parts = tLine.split('\t').filter(p => p.trim() !== '');

        if (parts.length >= 6) {
            const semester = parseInt(parts[parts.length - 1]);
            const sks = parseInt(parts[parts.length - 2]);

            let no = parseInt(parts[0]);
            let kode = '';
            let nama = '';

            if (!isNaN(no)) {
                kode = parts[1];
                nama = parts[2];
            } else {
                kode = parts[0];
                nama = parts[1];
            }

            nama = nama.replace(/'/g, "''");

            if (kode && nama && !isNaN(sks) && !isNaN(semester)) {
                let finalKategori = currentKategori;
                if (kode.startsWith('KU')) finalKategori = 'MKU';

                const uniqueKey = kode + '_' + finalKategori;

                if (sqlValuesMap.has(uniqueKey)) {
                    let existing = sqlValuesMap.get(uniqueKey);
                    if (existing.prodi !== currentProdi && existing.prodi !== 'Umum') {
                        existing.prodi = 'Umum';
                    }
                } else {
                    sqlValuesMap.set(uniqueKey, { kode, nama, sks, semester, prodi: currentProdi, kategori: finalKategori });
                }
            }
        }
    }

    let sql = 'TRUNCATE TABLE public."MataKuliah";\n\n';
    sql += 'INSERT INTO public."MataKuliah" (kode, nama, sks, semester_rekomendasi, prodi, kategori) VALUES\n';

    let isFirst = true;
    sqlValuesMap.forEach(v => {
        if (!isFirst) sql += ",\n";
        sql += "('" + v.kode + "', '" + v.nama + "', " + v.sks + ", " + v.semester + ", '" + v.prodi + "', '" + v.kategori + "')";
        isFirst = false;
    });

    sql += ';\n';

    fs.writeFileSync('seed_matkul_final.sql', sql);
    console.log("SQL generated at seed_matkul_final.sql");
}

parseData();
